import { Router } from "express"
const router=Router({ mergeParams: true })

router.route('/')
.get()
.post()
router.route('/:orgId')
.get()
.put()
.delete()
router.route('/:orgId/members')
.get()
.post()
router.route('/:orgId/members/:userId')
.get()
.delete()
router.route('/:orgId/members/:userId/role')
.patch()
router.route('/:orgId/invitations')
.get()
.post()
router.route('/:orgId/invitations/:invitationId')
.delete()
router.route('/invitations/:token/accept')
.post()
router.route('/:orgId/settings')
.get()
.put()

export default router